services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bmack\IssueTester\:
    resource: '../Classes/*'

  Bmack\IssueTester\DataGeneratorWorkspaceListener:
    tags:
      - name: event.listener
        identifier: 'issue-tester'
        event: TYPO3\CMS\Workspaces\Event\AfterDataGeneratedForWorkspaceEvent